### ISSUE TITLE
Add Nigiri 🙏?

### ISSUE THREAD

**Issue by tiero** [valerio-vaccaro/awesome-liquid#3]
Quickly fire up a regtest Bitcoin blockchain along with Liquid, Esplora, and Electrum for each node. You can run tests locally, use rpc interfaces.

Testnet and Mainnet will be released soon.

Website: https://nigiri.vulpem.com
Github: https://github.com/vulpemventures/nigiri

**Comment by valerio-vaccaro** [comment]
Consider update liquid/elements to 0.17 available at https://github.com/ElementsProject/elements/releases.

**Comment by tiero** [comment]
Done! https://github.com/vulpemventures/nigiri/releases

**Comment by valerio-vaccaro** [comment]
done
